[project]
name = "pibic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.1",
    "pip>=25.2",
    "scikit-learn>=1.7.1",
]
